Repository shanilpanara/origamiUROP, pull requests merged in 2020-07, with the labels that each got.

#4 Pytest and travis
  .travis.yml
  test/test_placeholder.py
Labels: deploy

#6 shanil polygon first attempt
  .travis.yml
  origamiUROP/__init__.py
  origamiUROP/cube.stl
  origamiUROP/hello.py
  origamiUROP/polygon 4.py
  origamiUROP/polygon.py
  origamiUROP/polygons.py
  polygons/STL/hexagon.stl
  polygons/STL/star.stl
  protocols/easy-shapes/main.py
  sandbox/THIS_FOLDER.txt
  test/test_polygons.py
Labels: geometry

#24 oxDNA setup for mrDNA simulations
  protocols/fiona_gen.py
Labels: dna

#30 lammps data output
  .gitignore
  origamiUROP/oxdna/nucleotide.py
  origamiUROP/oxdna/strand.py
  origamiUROP/oxdna/system.py
  test/test_lammps/test_lammps_01.py
  test/test_oxdna/test_strand.py
Labels: io, simulations

#39 Create DNAEdge class and init inheritance
  origamiUROP/lattice/__init__.py
  origamiUROP/lattice/_lattice.py
  origamiUROP/lattice/edge.py
  origamiUROP/lattice/node.py
  origamiUROP/lattice/route.py
  origamiUROP/oxdna/strand.py
  origamiUROP/oxdna/system.py
  origamiUROP/polygons.py
  origamiUROP/tools.py
  setup.py
  test/test_DNAGeometry.py
  test/test_lattice.py
Labels: dna, geometry
